services:
  mongodb:
    image: mongo:latest
    container_name: nammongodb-prod

    volumes:
      - mongodb_prod_data:/data/db

    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "--eval",
          "db.adminCommand('ping')"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped

  product-api:
    image: hotboisg12/product-api:latest
    container_name: product-api-prod

    pull_policy: always

    ports:
      - "3000:3000"

    environment:
      PORT: 3000
      MONGO_URI: mongodb://mongodb:27017/productdb

    depends_on:
      mongodb:
        condition: service_healthy

    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', r => process.exit(r.statusCode === 200 ? 0 : 1)).on('error', () => process.exit(1))"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    restart: unless-stopped

volumes:
  mongodb_prod_data: